<ul class="summary">
    <li class="chapter">
      <a href="README.md">
         Introduction
      </a>
    </li>
    <li class="chapter">
      <a href="helloworld.md">
         helloworld
      </a>
    </li>
    <li class="chapter">
      <a href="major_classes.md">
         major classes
      </a>
    </li>
    <li class="chapter">
      <a href="qt_designer.md">
         qt designer
      </a>
    </li>
    <li class="chapter">
      <a href="signals.md">
         signals
      </a>
    </li>
    <li class="chapter">
      <a href="layouts.md">
         layouts
      </a>
    </li>
    <li class="chapter">
      <a href="widgets.md">
         widgets
      </a>
    </li>
    <li class="chapter">
      <a href="dialog.md">
         dialog
      </a>
    </li>
    <li class="chapter">
      <a href="messageBox.md">
         messageBox
      </a>
    </li>
</ul>
